### PR TITLE
Fix entity leak (20% faster with that commit)

### PR DESCRIPTION
**Pull request by Misteboss**

### CODE REVIEW

**Comment by PmmpCorePro** [comment]
its look good , have you tested it ?

**Comment by Misteboss** [comment]
Yep (this is why it takes me 10 mins to pull rquest it)

**Comment by PmmpCorePro** [comment]
i see. thanks you so much!!

**Comment by PmmpCorePro** [comment]
we will really beat pmmp at this rate

**Comment by Misteboss** [comment]
Can I have perms now :p ? (New optimisation of 40% WIP)

**Comment by PmmpCorePro** [comment]
added ! welcome to team

**Comment by PmmpCorePro** [comment]
oh no i think this break somthing

**Pull request merged**
